In [7]:
import pandas as pd 
from jtwAndjte import clean_journey
from preprocess import preprocess_household, preprocess_person

In [8]:
edu = "../A2 datasets/journey_to_education_vista_2023_2024.csv"
work ="../A2 datasets/journey_to_work_vista_2023_2024.csv"
person = "../A2 datasets/person_vista_2023_2024.csv"
household = "../A2 datasets/household_vista_2023_2024.csv"

In [9]:
edu = clean_journey(edu, "edu.csv")
work = clean_journey(work, "work.csv")
person = preprocess_person(person)
household = preprocess_household(household)

/Users/phamthiphuongthuy/Desktop/Unimelb/Y2S1/EODP/eodp_a2/preprocess/preprocess.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f"perspoststratweight_GROUP_{number}"].fillna(mode_value[0], inplace=True)

In [10]:
# Merge household data onto person data using 'hhid'
demographic = person.merge(household, on='hhid', suffixes=('', '_household'))

# Remove duplicate columns if any
demographic = demographic.loc[:, ~demographic.columns.duplicated()]
demographic

,persid,hhid,travdow,agegroup,sex,carlicence,mbikelicence,otherlicence,nolicence,fulltimework,...,dayType,persinc_category,hhsize,dwelltype,owndwell,travdow_household,aveagegroup_5,hhinc_group,hhinc_category,homelga
0,Y24H5740102P01,Y24H5740102,Tuesday,30->34,Female,Full Licence,0,0,No,0,...,Weekday,low,2,"Unit, Flat or Apartment",Being Rented,Tuesday,25->29,1250,low,C
1,Y24H5740102P02,Y24H5740102,Tuesday,25->29,Male,Full Licence,0,0,No,0,...,Weekday,medium,2,"Unit, Flat or Apartment",Being Rented,Tuesday,25->29,1250,low,C
2,Y24H5740103P01,Y24H5740103,Wednesday,70->74,Female,Full Licence,0,0,No,0,...,Weekday,low,1,Separate House,Fully Owned,Wednesday,70->74,500,low,C
3,Y24H5740104P01,Y24H5740104,Thursday,55->59,Female,No Car Licence,0,0,Yes,0,...,Weekday,low,1,Separate House,Being Rented,Thursday,55->59,1,low,C
4,Y24H5740109P01,Y24H5740109,Tuesday,45->49,Male,Full Licence,0,0,No,0,...,Weekday,medium,5,Separate House,Being Purchased,Tuesday,25->29,2000,medium,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8170,Y24H6210434P02,Y24H6210434,Saturday,40->44,Male,Full Licence,0,0,No,1,...,Weekend,medium,2,Separate House,Being Purchased,Saturday,45->49,1000,low,C
8171,Y24H6210533P03,Y24H6210533,Friday,5->9,Male,No Car Licence,0,0,Yes,0,...,Weekday,low,4,Separate House,Being Purchased,Friday,20->24,2500,medium,S
8172,Y24H6210533P04,Y24H6210533,Friday,0->4,Female,No Car Licence,0,0,Yes,0,...,Weekday,low,4,Separate House,Being Purchased,Friday,20->24,2500,medium,S
8173,Y24H6220516P03,Y24H6220516,Tuesday,15->19,Female,No Car Licence,0,0,Yes,0,...,Weekday,low,5,"Unit, Flat or Apartment",Fully Owned,Tuesday,20->24,1500,low,C
8174,Y24H6230519P04,Y24H6230519,Friday,10->14,Male,No Car Licence,0,0,Yes,0,...,Weekday,low,4,Separate House,Fully Owned,Friday,25->29,2500,medium,S

In [11]:
# Add a label column to distinguish work and edu
work['journey_label'] = 1
edu['journey_label'] = 0

# Combine work and edu into a single DataFrame
journey = pd.concat([work, edu], ignore_index=True)
journey

,hhid,persid,dayType,main_journey_mode,journey_travel_time,journey_distance,journey_elapsed_time,journey_weight,homesubregion_ASGS,homeregion_ASGS,wasted_time,journey_label
0,Y24H5740102,Y24H5740102P02,Weekday,vehicle driver,25,12.89117,25.0,652.818031,melb - outer,greater melbourne,0.0,1
1,Y24H5740109,Y24H5740109P02,Weekday,vehicle driver,4,1.33689,4.0,760.235358,melb - outer,greater melbourne,0.0,1
2,Y24H5740110,Y24H5740110P03,Weekday,vehicle passenger,10,9.42059,10.0,603.756454,melb - outer,greater melbourne,0.0,1
3,Y24H5740111,Y24H5740111P01,Weekday,vehicle driver,30,20.87897,30.0,348.746406,melb - outer,greater melbourne,0.0,1
4,Y24H5740111,Y24H5740111P02,Weekday,vehicle driver,140,189.08695,147.0,696.781612,melb - outer,greater melbourne,7.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2476,Y24H6250412,Y24H6250412P03,Weekday,vehicle passenger,12,2.99861,19.0,3521.027609,melb - middle,greater melbourne,7.0,0
2477,Y24H6250412,Y24H6250412P04,Weekday,vehicle passenger,5,1.79146,5.0,934.030123,melb - middle,greater melbourne,0.0,0
2478,Y24H6250423,Y24H6250423P02,Weekday,vehicle passenger,5,0.80955,5.0,403.663553,melb - middle,greater melbourne,0.0,0
2479,Y24H6250438,Y24H6250438P03,Weekday,vehicle passenger,5,1.18675,5.0,439.369597,melb - middle,greater melbourne,0.0,0
2480,Y24H6250438,Y24H6250438P04,Weekday,vehicle passenger,5,1.18675,5.0,743.933779,melb - middle,greater melbourne,0.0,0

In [14]:
merged_data = journey.merge(demographic, on=['persid', 'hhid'], suffixes=('_journey', '_demographic'))
merged_data = merged_data.loc[:, ~merged_data.columns.duplicated()]
merged_data.drop(["homesubregion_ASGS_demographic","homeregion_ASGS_demographic","dayType_demographic", "travdow_household"],axis=1, inplace=True)
merged_data.to_csv("merged_data.csv", index=False)